version: '3.8'

services:
  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "8080:80"
    volumes:
      - ./out:/usr/local/apache2/htdocs/energieportal/
    restart: unless-stopped
