import type { Meta, StoryObj } from '@storybook/react';
import Overlay from './overlay';
import { Button } from '../button/button';
import { Accordion } from '../accordion/accordion';

const meta: Meta<typeof Overlay> = {
  title: "Components / Overlay",
  component: Overlay,
};

export default meta;
type Story = StoryObj<typeof Overlay>;

export const Default: Story = {
    render: () => (
        <>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas feugiat placerat risus eu tristique. Quisque a auctor elit. Nam ut pellentesque diam. In gravida vel orci id volutpat. Praesent ut mi quis elit facilisis commodo. Quisque feugiat elit nibh, viverra dignissim nisi tristique placerat. Praesent ligula felis, scelerisque eget sodales condimentum, commodo vel ante. Vestibulum ut scelerisque nulla. In fringilla, neque vel efficitur sollicitudin, sem justo finibus velit, vel sagittis velit quam laoreet lacus. Duis rutrum molestie lectus vitae viverra. Phasellus ut sagittis lorem. Aliquam dolor ligula, lacinia vel mi convallis, ornare finibus lorem.
            Quisque lorem dolor, maximus nec enim id, pretium finibus magna. Praesent cursus lectus tellus. Integer ut elit euismod, placerat sem in, malesuada lectus. Proin suscipit, lorem in rutrum interdum, nunc ipsum ullamcorper sem, ut dignissim purus tortor molestie odio. Vestibulum quis gravida libero. Nullam tempus, odio eu tristique tincidunt, metus arcu laoreet felis, ut volutpat urna orci eu lorem. Donec scelerisque at massa id lacinia. Vivamus vel eleifend odio.
            <Overlay trigger={<Button>Open Overlay</Button>}>
                Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
                <Accordion summary={"Accordion"}>
                    Blablabla
                </Accordion>
            </Overlay>
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
            Cras venenatis luctus massa sit amet dapibus. Sed fermentum sapien sed diam porttitor, vel tincidunt nisl euismod. Quisque felis risus, tincidunt id lorem vel, lacinia consectetur arcu. Suspendisse vitae dapibus nisi. Nulla vel odio placerat, varius erat sed, rutrum metus. Quisque a eros vulputate ligula aliquam rhoncus. Curabitur sit amet nibh scelerisque, accumsan velit sed, suscipit ipsum. Mauris eget tempus lectus, ac consectetur nulla. Nunc congue urna sit amet tincidunt sollicitudin. Sed at congue turpis. Etiam efficitur in felis nec interdum. Nulla facilisi.
            Fusce varius magna et vestibulum iaculis. Nam commodo vel mi at interdum. Aenean eget nulla neque. Curabitur magna nisi, rutrum sit amet porttitor eget, aliquet eget massa. Sed at lacus tortor. Maecenas efficitur lectus in lacus ornare, ac pellentesque quam tincidunt. Sed at diam sed lacus volutpat euismod. Integer vitae hendrerit purus. Proin pellentesque justo ut elit lacinia convallis.
            Morbi maximus, nulla sit amet tincidunt eleifend, enim velit sollicitudin neque, ac tristique est lorem quis mi. Nullam interdum tortor eu lorem molestie, a placerat ex vehicula. Sed ac posuere augue. Proin vestibulum justo sit amet pretium luctus. Vestibulum placerat vel leo vulputate varius. Curabitur quis tristique nisi. Aliquam at lectus sollicitudin, congue nulla at, imperdiet urna. Aenean laoreet dapibus est congue tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras vehicula semper lectus, facilisis congue mi porttitor vitae. Phasellus quis mi lacus. Nam euismod condimentum magna. Curabitur et facilisis mauris, nec ornare ante. Duis blandit ipsum ut vestibulum aliquet.
        </>
    )
};
